// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEuEqXryRQIUl0UutMQrpgki-NlqWOMt8',
    appId: '1:10867894388:web:705eb54299ddd9fe718921',
    messagingSenderId: '10867894388',
    projectId: 'fir-flutter-codelab-66f38',
    authDomain: 'fir-flutter-codelab-66f38.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-66f38.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXz-Xh46rWIoAqKVAIOpT2DSJ0PLEfkAk',
    appId: '1:10867894388:android:aa06f1646104a3c2718921',
    messagingSenderId: '10867894388',
    projectId: 'fir-flutter-codelab-66f38',
    storageBucket: 'fir-flutter-codelab-66f38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGkNtAMmkLsLB4UeJq4hdx7Giu15JsFu4',
    appId: '1:10867894388:ios:1afd797326f73238718921',
    messagingSenderId: '10867894388',
    projectId: 'fir-flutter-codelab-66f38',
    storageBucket: 'fir-flutter-codelab-66f38.appspot.com',
    iosClientId: '10867894388-ua0dcbtue2eelotfb5soei6l6q401t0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGkNtAMmkLsLB4UeJq4hdx7Giu15JsFu4',
    appId: '1:10867894388:ios:1afd797326f73238718921',
    messagingSenderId: '10867894388',
    projectId: 'fir-flutter-codelab-66f38',
    storageBucket: 'fir-flutter-codelab-66f38.appspot.com',
    iosClientId: '10867894388-ua0dcbtue2eelotfb5soei6l6q401t0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
